services:
    postgres:
        container_name: service-postgres
        image: postgres:16
        environment: &db_env
          POSTGRES_DB: split_bill
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - "32769:5432"
        volumes:
          - ./postgresql/schemas:/docker-entrypoint-initdb.d
          - pgdata:/var/lib/postgresql/data
        networks:
          - postgres
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U user -d split_bill"]
          interval: 5s
          retries: 5
          start_period: 10s

    app-container:
        image: ghcr.io/userver-framework/ubuntu-22.04-userver-pg:latest
        privileged: true
        environment:
          <<: *db_env
          PREFIX: /home/user/.local
          CCACHE_DIR: /split_bill/.ccache
          CORES_DIR: /cores
        volumes:
          - .:/split_bill:rw
          - ${TC_CORES_DIR:-./.cores}:/cores:rw
        ports:
          - 8080:8080
        working_dir: /split_bill
        entrypoint:
          - ./tests/run_as_user.sh
        depends_on:
          postgres:
            condition: service_healthy
        networks:
          - postgres

networks:
    postgres:
        driver: bridge

volumes:
    pgdata: